apiVersion: v1
kind: PersistentVolume
metadata:
  name: wildfly-pv
  labels:
    type: local
    app: wildfly
    namespace: ubuntu-test
    storage-tier: pv1-wildfly
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/wildfly
